[dev]
  command = "pnpm dev"
  framework = "astro"

[build]
  command = "pnpm build"
  publish = "dist"

[[redirects]]
  from = "/root"
  to = "https://app.fndtns.org/root"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true